export const skills = [
    { title: "前端設計", value: ["HTML", "CSS：Scss、Sass", "UI框架：Bootstrap、MUI、Tailwind、Antd"] },
    { title: "前端測試", value: ["單元測試：Jest", "React Testing Library"] },
    { title: "資料庫", value: ["MongoDB", "Oracle SQL"] },
    { title: "JS / 前端框架 / 後端框架", value: ["jQuery", "React.js：React Hook、Redux、Next.js、Vite.js", "Vue.js", "Ajax / Axios：串接 API ", "Node.js", "Flask"] },
    { title: "其他工具", value: ["版本控制：Git", "線框搞：Whimsical、Figma", "視覺設計：Illustrator/PhotoShop", "Python", "VBA"] },
    { title: "英文能力：多益750分", value: [] },
]


export const projects = [
    { name: "Profolio", 
        src: "/images/Profolio",
        img: 1,
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet."] },
    { name: "BookingHotel", 
        src: "/images/BookingHotel",
        img: 8,
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet."] },
    { name: "Car Showcase", 
        src: "/images/CarShowcase",
        img: 3,
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet."] },
    { name: "Blog", 
        src: "/images/Blog",
        img: 4,
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet."] },
    { name: "Todos", 
        src: "/images/Todos",
        img: 3,
        desc: ["Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet.", 
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Accusamus aperiam sapiente cumque, voluptates non provident. Quia eum aliquid ex doloremque assumenda laboriosam soluta, repellat qui id eos debitis dolor eveniet."] },
]